package waltomadaam2.xinbot.playermonitor;

record DatabaseHealth(
        String writerState,
        boolean writerAlive,
        boolean writerRecovering,
        boolean writerStalled,
        int queueSize,
        int queueCapacity,
        int queueHighWaterMark,
        int queueDelta1m,
        int queueDelta5m,
        long lastCommittedAt,
        long lastChatCommittedAt,
        long lastSessionCommittedAt,
        long lastStatCommittedAt,
        long lastUuidWrittenAt,
        long lastFailureAt,
        String lastFailureMessage,
        long writerRecoveryCount,
        long chatCommitted,
        long chatDbFailed,
        long chatQueueRejected,
        long failedEventPersistFailures,
        long failedEventLines,
        long replayedFailedEvents,
        long pendingFailedEvents,
        long malformedFailedEvents,
        long databaseBytes,
        long walBytes,
        long shmBytes) {
}
